---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 4
  selector:
    app: rk
  template:
    metadata:
      labels:
        app: rk
    spec:
      containers:
      - name: my-cont1
        image: kudipudirk/dm-site
        ports:
          - containerPort: 80
