---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rk
  template:
    metadata:
      labels:
        app: rk
    spec:
      containers:
       - name: my-cont2
         image: kudipudirk/game-site
         ports:
           - containerPort: 80
